tests: bump cryptography to 2.2.1
With version 2.0.3 the following happens:

> import requests
> requests.get('https://weblate.securedrop.org/exports/stats/securedrop/securedrop/?format=json')
From cffi callback <function _verify_callback at 0x7f18204d15f0>:
Traceback (most recent call last):
  File "/home/loic/software/securedrop/virtualenv/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'

and also in other contexts. Upgrading to 2.2.1 fixes the problem.